### PR TITLE
Added new testimonial quote for whitney

### PR DESCRIPTION
**Pull request by sylvercodez**

### CODE REVIEW

**Review by ashlchap — COMMENTED** [review]
Hi @sylvercodez -- the lower part of her face is cut out of the photo on the website, but it's not in the original. Is it possible for you to crop /adjust the photo so that when you post it, we see her full face? pls let me know. Thanks!

**Comment by sylvercodez** [comment]
@ashlchap yes sure. I will effect the correction now.

**Review by ashlchap — COMMENTED** [review]
Hi @sylvercodez - I'm not sure if you've made more changes, but when I look at the photo the staging site, her neck,etc is still cut off. Could you make sure that the photo on the staging site shows her head and her neck? (It should look like a normal headshot!) THanks

**Review by ashlchap — COMMENTED** [review]
Oh - apologies, I just saw your new photo via what's app! It looks much better but now the photo looks slightly warped, like it was stretched. Is it possible just to crop it without doing that? if not, it's fine. Thank yoU!

**Comment by sylvercodez** [comment]
The image width is lower than the testimonial design width that's why it is
looking wrapped.

I am not sure there is a better way

**Pull request closed without merging**
