### PR TITLE
fix for enrolling is easy text

### PR DESCRIPTION
**Pull request by sylvercodez**

### CODE REVIEW

**Review by ashlchap — CHANGES_REQUESTED** [review]
Sorry Tobi, can you pls add  "LinkedIn strategist" before Teddy Burriss? See below:

...."watch this video (insert link) with LinkedIn strategist, Teddy Burriss, to get some topline tips."

**Comment by sylvercodez** [comment]
@ashlchap can you check this please

**Comment by ashlchap** [comment]
@sylvercodez - pls add a comma after Teddy Burriss, which I had in my original. Correct version below. Thanks:

Watch [this video ](https://www.youtube.com/watch?v=iubjqvaqZHM)with LinkedIn strategist, Teddy Burriss, to get some topline tips)

**Comment by ashlchap** [comment]
@sylvercodez - pls add a comma after Teddy Burriss, which I had in my original. Correct version below. Thanks:

Watch [this video ](https://www.youtube.com/watch?v=iubjqvaqZHM)with LinkedIn strategist, Teddy Burriss, to get some topline tips)

**Comment by ashlchap** [comment]
> @ashlchap can you check this please

@sylvercodez - pls add a comma after Teddy Burriss, which I had in my original. Correct version below. Thanks:

Watch [this video ](https://www.youtube.com/watch?v=iubjqvaqZHM)with LinkedIn strategist, Teddy Burriss, to get some topline tips)

**Review by ashlchap — APPROVED** [review]

**Pull request merged**
