### PR TITLE
Add Ese Sifo to advisory board on about page

### LINKED ISSUE #181: About Us page: please post this advisory board member
Hi Tobi or Alex:
For some reason, Ese Sifo was dropped from our advisory board on our About Us page. Can you please post the bio below, his quote on the landing page, (per the others) and his photo? See instructions below. Thank you!

To post under Advisory Board on ABOUT US page:
*********
Ese Sifo

(title that goes ON his photo): 
Global Director, HR, Nordson Corp.

(Quote that goes below his photo, italicized to match the others):  
"I’m passionate Reskill Americans' mission because I want to help create a path for people like me who might not necessarily get access to an education in tech, so that ultimately, all communities have a seat at the table in tech industry."

(Posted LinkedIn icon, on this page, per the others): https://www.linkedin.com/in/esesifo/

Then, when you click into this bio (landing page for his bio) please post:

Ese Sifo
Global Director, HR, Nordson Corp.

Ese Sifo serves as the Global Director of Human Resources for Nordson Corporation where he is responsible for creating a people strategy that helps to drive business objectives for the company. He also serves as Talent & HR Advisor to Reskill Americans. Ese began his career in finance but quickly pivoted to Human Resources after he identified a need for corporations to attract, develop and engage diverse talent and promote inclusive and equitable practices in the work place to afford minorities a chance at career development and progression. In his spare time, Ese coaches young adults with medical complications who are looking to grow their career objectives and fulfill their purpose.  Ese is passionate about this project given his own struggles with Sickle Cell Anemia while rising in his professional career to leadership positions.
 
“I believe that a career in tech is key to the future. I have two boys who I am trying to prepare for the future workforce. I’m passionate about the mission of Reskill Americans because I want to help create a path for people like me who might not necessarily get access to an education in tech so that ultimately, all communities have a seat at the table in tech industry." 

"Throughout my life, I have found that being able to give back to my community is where I find purpose.  Reskill Americans provides an opportunity for me to do just that.”

(post) LinkedIn: https://www.linkedin.com/in/esesifo/

Photo: 
https://netorgft7227627.sharepoint.com/sites/RSA2022/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FRSA2022%2FShared%20Documents%2FCommunications%2FWebsite%2F2021%20Site%20Redesign%20Copy%2Fcontent%2Fabout%2FEse%2Ejpg&parent=%2Fsites%2FRSA2022%2FShared%20Documents%2FCommunications%2FWebsite%2F2021%20Site%20Redesign%20Copy%2Fcontent%2Fabout

image

### PR DESCRIPTION
**Pull request by AlexMNet**
Add Ese Sifo to advisory board on about page
Closes #181

### CODE REVIEW

**Review by ashlchap — CHANGES_REQUESTED** [review]
Thanks @AlexMNet! Ok, don't kill me, but I just realized that his quote below his photo is a run on sentence, and there's a period missing at the end of the final quote. Could you please change as follows: Use this quote below for under his photo instead: 

"I believe that a career in tech is key to the future. I have two boys who I am trying to prepare for the future workforce." 

Then, for the full quote below his bio on his landing page, please replace with the below, as I've made small edits:

"I believe that a career in tech is key to the future. I have two boys who I am trying to prepare for the future workforce. I’m passionate about the mission of Reskill Americans because I want to help create a path for people like me, who might not necessarily get access to an education in tech, so that ultimately, all communities have a seat at the table in tech industry.
Throughout my life, I have found that being able to give back to my community is where I find purpose. Reskill Americans provides an opportunity for me to do just that."

**Comment by AlexMNet** [comment]
@ashlchap No worries! The PR has been updated to reflect you changes! Don't hesitate to let me know if there is anything else you need!

**Review by ashlchap — APPROVED** [review]

**Comment by ashlchap** [comment]
Thanks Alex!!

**Comment by AlexMNet** [comment]
@ashlchap im away from the computer but I think you closed the PR

**Pull request merged**
