### PR TITLE
Test dev

### PR DESCRIPTION
**Pull request by sylvercodez**

### CODE REVIEW

**Comment by sylvercodez** [comment]
@mckoss  i have re-pushed and it has been deployed you can also check the mobile view

**Comment by mckoss** [comment]
Images look stretched to me?  Perhaps should use:

object-fit: cover.

**Comment by sylvercodez** [comment]
oh ok will correct that right now

**Comment by sylvercodez** [comment]
but i also noticed the images are not of same size, some images will cut with object :cover

**Pull request closed without merging**
